### ISSUE TITLE
qryn references

### ISSUE THREAD

**Issue by lmangani** [go-faster/oteldb#364]
Hello there fellow developers! We're big go-faster fans at metrico and I noticed you're comparing directly against our project [qryn](https://github.com/metrico/qryn) in some of your [dev testing](https://github.com/go-faster/oteldb/blob/5a180415443fdefb1913b316e3dca91ea6a0105c/dev/local/ch-full/docker-compose.yml#L21) and use our otel-collector as well which seems quite interesting :) Any reason why you're testing against our patiently created API and ClickHouse integration rather than against the originals (Loki, Prometheus, Tempo) you advertise compatibility with? This project essentially seems to elegantly reimplement a subset of our features so it would be interesting to find ways to cooperate rather than duplicate if we're sharing similar goals in opensource :)  Feel free to drop in our [matrix channel](https://matrix.to/#/#qryn:matrix.org) if you'd ever like to reach out. Thanks for your time in advance! 👋

**Comment by lmangani** [comment]
Self-Closing since this is just a crossover question to avoid it mixed with actual issues 🙃

**Comment by ernado** [comment]
Hi, thank you for discovering those references, I've forgot to remove them :smiling_face_with_tear: 

> Any reason why you're testing for compatibility against our patiently created API and ClickHouse integration rather than against the originals

This was an artifact of our effort to explore compatibility testing with our fork of [promql-compliance-tester](https://github.com/go-faster/oteldb/blob/main/cmd/promql-compliance-tester/main.go) and our generated Loki/Prometheus/Tempo [proxy](https://github.com/go-faster/oteldb/blob/main/cmd/otelproxy/main.go). 

We've also testing against original implementations as well as other protocol-compatible ones.

> elegantly reimplement

The oteldb project does not aim to reimplement qryn and was started as an big R&D around ways to create an OpenTelemetry compatible observability storage.

Originally it [was based](https://github.com/go-faster/oteldb/blob/4d7995111f214728aa3a3a5ad1584e4b03582315/README.md?plain=1#L15-L18) on  [YTSaurus](https://ytsaurus.tech) distributed storage, but later we switched to ClickHouse.

> a subset of our features 

The oteldb project strictly follows prometheus compatibility:

```
# qryn
Total: 55 / 547 (10.05%) passed, 0 unsupported
```
![qryn](https://github.com/go-faster/oteldb/assets/866677/abf3d294-af70-4218-b079-0dbf4df4180f)


```
# oteldb
Total: 546 / 547 (99.82%) passed, 0 unsupported
```
![oteldb](https://github.com/go-faster/oteldb/assets/866677/eb214b7b-9068-4051-8560-1166813fc341)


> if we're sharing similar goals in opensource

The go-faster and oteldb projects are not seeking any commercialization or business model and primarily use Apache 2.0 license, so our efforts are unlikely to be compatible with any open core solutions like Victoria Metrics or qryn nor AGPL/BSL-like licenses.

I've removed all references to qryn to reduce confision, sorry for inconvenience.
