### ISSUE TITLE
feat(observability): instrument all subsystems

### ISSUE THREAD

**Issue by ernado** [go-faster/oteldb#64]
All subsystems should be instrumented with tracer and meter, so every constructor should accept `TracerProvider` and `MeterProvider`.

So, needed in general:
- Basic metrics (i.e. logs/traces received)
- Reasonable coverage with spans

**Comment by tdakkota** [comment]
1) OpenTelemetry collector is pretty much instrumented by [`obsreport`](https://pkg.go.dev/go.opentelemetry.io/collector/obsreport).
2) Querying APIs are instrumented by ogen and otelhttp middleware.
3) Database clients are instrumented as well.

Not sure what exactly should be done.

**Comment by ernado** [comment]
E.g. storage methods, like this:

https://github.com/go-faster/oteldb/blob/8a899b02501da3a16b04ba5f05149adf2b4bf6a7/internal/ytstorage/ytql_querier_logs.go#L54-L87

**Comment by ernado** [comment]
Also probably `ytIterator` itelf.

I.e. places where non-trivial work with I/O is executed.

**Comment by ernado** [comment]
This should be mostly done.
